---
- name: Install Docker on private instances
  hosts: all
  become: yes
  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started
